#!/usr/bin/env python

# this is a script to filter the counts matrix generated by VERSE

import argparse
import pandas

parser = argparse.ArgumentParser()
parser.add_argument("-i", "--input", help='The input file specified will be the concatenated VERSE matrix provided by snakemake',dest="input", required=True)
parser.add_argument("-o", "--output", help='The output file name and path provided by snakemake',dest="output", required=True)
args = parser.parse_args()


df = pandas.read_csv(args.input)

sample_cols = [col for col in df.columns if col != 'gene']

filtered = df.loc[((df[sample_cols[0:3]] != 0).sum(axis=1) >= 2) & ((df[sample_cols[3:7]] != 0).sum(axis=1) >= 2)]

filtered.to_csv(args.output, index=False)

